### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [wafflespeanut/nucleic-acid#2]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by wafflespeanut** [comment]
Sorry, I don't even recall seeing this issue (until now). You're right. Only the bits vector seems to be using it, and yeah, it's probably not necessary in the first place. Thanks 😄
